/** Major cities and municipalities of Nepal for branch location picker. */
export const NEPAL_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Lalitpur",
  "Bhaktapur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Butwal",
  "Dharan",
  "Nepalgunj",
  "Hetauda",
  "Janakpur",
  "Dhangadhi",
  "Itahari",
  "Siddharthanagar",
  "Ghorahi",
  "Tulsipur",
  "Kalaiya",
  "Jitpur Simara",
  "Rajbiraj",
  "Lahan",
  "Damak",
  "Mechinagar",
  "Kirtipur",
  "Madhyapur Thimi",
  "Bidur",
  "Banepa",
  "Dhulikhel",
  "Panauti",
  "Birendranagar",
  "Tikapur",
  "Bhimdatta",
  "Waling",
  "Putalibazar",
  "Tansen",
  "Baglung",
  "Beni",
  "Kushma",
  "Gorkha",
  "Bandipur",
  "Chitwan",
  "Bhairahawa",
  "Lamahi",
  "Kohalpur",
  "Attariya",
  "Surkhet",
  "Ilam",
  "Phidim",
  "Dhankuta",
  "Bhadrapur",
  "Inaruwa",
  "Urlabari",
  "Belbari",
  "Gaighat",
  "Katari",
  "Sindhuli",
  "Ramechhap",
  "Dolakha",
  "Charikot",
  "Melamchi",
  "Baneshwor",
  "Kaushaltar",
  "Thimi",
  "Patan",
  "Nawalparasi",
  "Parasi",
  "Kawasoti",
  "Gaindakot",
  "Bardibas",
  "Jaleshwar",
  "Malangwa",
  "Gaur",
  "Chandranigahapur",
  "Gulariya",
  "Rajapur",
  "Musikot",
  "Jumla",
  "Dunai",
  "Simikot",
  "Darchula",
  "Dadeldhura",
  "Baitadi",
  "Amargadhi",
  "Dipayal",
  "Mangalsen",
  "Sandhikharka",
  "Tamghas",
  "Burtibang",
  "Myagdi",
  "Jomsom",
  "Manang",
  "Namche Bazaar",
  "Lukla",
  "Okhaldhunga",
  "Solu",
  "Khandbari",
  "Chainpur",
  "Bhojpur",
  "Diktel",
  "Salleri",
] as const

export type NepalCity = (typeof NEPAL_CITIES)[number]

export function filterNepalCities(query: string, limit = 12): string[] {
  const q = query.trim().toLowerCase()
  if (!q) return NEPAL_CITIES.slice(0, limit)
  const starts: string[] = []
  const contains: string[] = []
  for (const city of NEPAL_CITIES) {
    const lower = city.toLowerCase()
    if (lower.startsWith(q)) starts.push(city)
    else if (lower.includes(q)) contains.push(city)
    if (starts.length + contains.length >= limit * 2) break
  }
  return [...starts, ...contains].slice(0, limit)
}
